### PR TITLE
Fixed Loan Increase Main Transaction Issue

### LINKED ISSUE #2981: [BUG in Adding transaction in Loan Account]
### Please confirm the following

- [x] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Hello, there is a bug in the Demo version 4.5.0(150) of the Ivy wallet.

When adding a loan account, for example, lending $500 to a person from an account in the app and marking it as a main transaction, it correctly shows as an expense on the main page.

However, if we increase the loan amount by lending $200 more to the same person without clearing the previous balance and mark it as a main transaction, the app incorrectly categorizes it as an income transaction on the main and account pages. It should be recognized as an expense, as we are lending more money. Currently, the amount increases instead of decreasing.

Please fix this issue.

### To Reproduce

1.) I lended $400 to a person 'A' with my bank 'ABC'
 And when I see this transaction in the bank 'ABC' ledger in the Account section . It shows as this transaction as an expense (debit) transaction. And it is good and expected output.

2.)  But If I again add $100 as **Increase** in lending amount,  it means I have given more money to the same person. 

This time also the amount in the bank account from where I have given the amount to that person should be decreased.

But when we check the transaction in the bank section we find the amount got increased instead of decreasing.

### Expected behavior

Expected behaviour

The amount in the main bank account from where we have lended the person once again that transaction should also be marked as debit transaction (expenses Transaction)

### Screenshots

Screenshot_20240223-011003
Screenshot_20240223-012004
Screenshot_20240223-012024

### Smartphone

Pixel 6a

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?

Describe with a few bullets **what's new:**
- a Fixed the Issue where wrong transaction type was selected when loan increase was selected
- b Fixed Issue where Transaction was not displayed if empty note was selected in Loans
- c

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b

**In what cases your code won't work?**

- a
- b

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2981 

> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt [hunk 1]
```diff
@@ -16,4 +16,6 @@ fun <T> LoanRecordType.processByType(decreaseAction: () -> T, increaseAction: ()
         LoanRecordType.DECREASE -> decreaseAction()
         LoanRecordType.INCREASE -> increaseAction()
     }
-}
\ No newline at end of file
+}
+
+fun defaultLoanRecordType(): LoanRecordType = LoanRecordType.DECREASE
```
Comment (ILIYANGERMANOV) [inline shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt:21]: Let's directly use `LoanRecordType.DECREASE` instead of this function cuz it's simpler, shorter and more straightforward to understand

Comment (ILIYANGERMANOV) [reply shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt:21]: @Vishwa-Raghavendra ping me when you've resolved it so we can merge

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt [hunk 2]
```diff
@@ -393,7 +394,7 @@ private fun save(
 ) {
     if (loanRecord != null) {
         val record = loanRecord.copy(
-            note = noteTextFieldValue.text.trim(),
+            note = NotBlankTrimmedString.from(noteTextFieldValue.text).getOrNull()?.value,
```
Comment (ILIYANGERMANOV) [inline temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt:397]: Nice 💯

File: shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt (hunk 1 above)
Comment (Vishwa-Raghavendra) [reply shared/base/src/main/java/com/ivy/base/model/LoanRecordType.kt]: Hey @ILIYANGERMANOV 
Update the code with requested changes,
