### PR TITLE
Fix issue 3116

### LINKED ISSUE #3116: [BUG] Wallet Balance widget UI being cut
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Actually the buttons on the widget is cutting slightly. It cut the bottom

### To Reproduce

1. 

### Expected behavior

Want to display button fully

### Screenshots

Screenshot_2024-04-10-21-14-30-92_b783bf344239542886fee7b48fa4b892

### App version

4.6.2  From Google Playstore

### Smartphone

OnePlus Nord CE 2 5G 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by isaacnguyen0809**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

## Screen Recording
Small Phone

https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/f0252e48-6a28-4723-9e1b-70b04518c0c6

Large Phone

https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/60d6688b-07bb-4140-b417-770f98625e32

## What's changed?
+ Storing balance, income, expense with double instead of string before
+ UI improvements for app wdiget
+ Fix some spelling errors in source code

## Risk Factors
No for now 

- Closes #3116

### CODE REVIEW

File: widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt [hunk 1]
```diff
@@ -55,17 +55,17 @@ class WalletBalanceWidget(
         provideContent {
             val prefs = currentState<Preferences>()
             val appLocked = prefs[booleanPreferencesKey("appLocked")] ?: false
-            val balance = prefs[stringPreferencesKey("balance")] ?: "0.00"
+            val balance = prefs[doublePreferencesKey("balance")] ?: 0.00
             val currency = prefs[stringPreferencesKey("currency")] ?: "USD"
-            val income = prefs[stringPreferencesKey("income")] ?: "0.00"
-            val expense = prefs[stringPreferencesKey("expense")] ?: "0.00"
+            val income = prefs[doublePreferencesKey("income")] ?: 0.00
```
Comment (ILIYANGERMANOV) [inline widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt:60]: Use different names for the keys so there are no crashes like "income_v2", otherwise it'll crash for existing users

File: widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt [hunk 2]
```diff
@@ -55,17 +55,17 @@ class WalletBalanceWidget(
         provideContent {
             val prefs = currentState<Preferences>()
             val appLocked = prefs[booleanPreferencesKey("appLocked")] ?: false
-            val balance = prefs[stringPreferencesKey("balance")] ?: "0.00"
+            val balance = prefs[doublePreferencesKey("balance")] ?: 0.00
```
Comment (ILIYANGERMANOV) [inline widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt:58]: Extract the keys names as constants

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Extract keys as constants and rename them to `_v2` to prevent crashes caused by having stored string

**Comment by ILIYANGERMANOV** [comment]
@isaacnguyen0809 overall, very good and clean PR 💯 To fix the videos in the PR desc just add a new line

File: widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt [hunk 3]
```diff
@@ -35,6 +35,11 @@ import javax.inject.Inject
 import kotlin.math.abs
 
 const val THOUSAND = 1000
+const val APP_LOCKED = "appLocked"
+const val BALANCE_V2 = "balance_v2"
```
Comment (ILIYANGERMANOV) [inline widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt:39]: Remove the `_V2` from the constant name. The make the code simpler you can in the same file create:
```kotlin
object DataStoreKeys {
   const val AppLocked = "..."
   const val Balance = "balance_v2"
}
```

Comment (isaacnguyen0809) [reply widget/balance/src/main/java/com/ivy/widget/balance/WalletBalanceWidget.kt]: Updated

**Review by ILIYANGERMANOV — APPROVED** [review]
Great job 💯 Merging after the CI pass
