### PR TITLE
Fix for issue #3202

### LINKED ISSUE #3202: App doesn't keep chosen date [BUG]
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When I enter new expense and choose the date, the app changes it for today's date instead of chosen date.

### To Reproduce

1. Enter new expense
2. Save it using any date but today
3. Review it, it will show today's date instead of the one you chose.

### Expected behavior

_No response_

### Screenshots

_No response_

### App version

4.6.2 google play

### Smartphone

Samsung galaxy z flip 5

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by suyash01**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?

Describe with a few bullets **what's new:**
- now the date reflects correctly on the date picker if selecting more than once
- b
- c

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b

**In what cases your code won't work?**

- a
- b

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3202 

> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

https://github.com/Ivy-Apps/ivy-wallet/assets/18034836/9dc4d6fd-1d9e-4b17-acda-aac733454422

### CODE REVIEW

File: app/src/main/java/com/ivy/wallet/RootActivity.kt [hunk 1]
```diff
@@ -159,7 +159,11 @@ class RootActivity : AppCompatActivity(), RootScreen {
                 onDatePicked ->
             val datePicker =
                 MaterialDatePicker.Builder.datePicker()
-                    .setSelection(MaterialDatePicker.todayInUtcMilliseconds())
+                    .setSelection(
+                        if(initialDate == null)
```
Comment (ILIYANGERMANOV) [inline app/src/main/java/com/ivy/wallet/RootActivity.kt:163]: Can you flip the `if (initialDate != null)` so the code is more readable

**Review by ILIYANGERMANOV — APPROVED** [review]
Fix the CI and my comment and we can merge 💯

File: app/src/main/java/com/ivy/wallet/RootActivity.kt (hunk 1 above)
Comment (suyash01) [reply app/src/main/java/com/ivy/wallet/RootActivity.kt]: made the change
