### PR TITLE
fix: removed csvFormat() and kept UTC format

### LINKED ISSUE #3422: [BUG] Incorrect time shown in exported csv file
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

This is a transaction in the Ivy Wallet app
[Image 1]
And this is the same transaction in the csv file. 
[Image 2]
I think this issue might be related to #3402 

### To Reproduce

1. Go to settings
2. Export CSV File
3. Some transactions have incorrect time.

### Expected behavior

_No response_

### Image 1
WhatsApp Image 2024-08-23 at 13 30 49_590b7206
### Image 2
image

### App version

v2024.07.28(194) from Google Play

### Smartphone

Poco F3 GT, Android 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akashs056**
## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of your changes (if applicable):
WhatsApp Image 2024-08-24 at 13 21 55_f9f86d96

## What's changed?

I have updated the code to remove the csvFormat() function and instead kept the UTC format with the "Z" for both date and dueDate. After testing, it works perfectly fine and correctly handles the UTC time. The export and import processes function smoothly without any issues.

## Does this PR close any GitHub issues? (do not delete)

- Closes #3422

### CODE REVIEW

File: shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt [hunk 1]
```diff
@@ -74,7 +74,7 @@ class ExportCsvUseCase @Inject constructor(
         categoriesMap: Map<CategoryId, Category>,
     ): String = csvRow {
         // Date
-        csvAppend(date?.csvFormat())
+        csvAppend(date?.toString())
```
Comment (ILIYANGERMANOV) [inline shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: This might break the CSV, I don't feel confident that it'll work

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: For example some user Locales may export it with `,` which will result in broken CSV. What's the issue with .csvExport()?

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: Also users prefer to see their CSV time in their local time (given that the local time is correct)

Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: Thanks for the feedback! I'll switch back to .csvFormat() and adjust it to export the time in the user's local time zone while keeping the format consistent and CSV-safe.

Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: > For example some user Locales may export it with `,` which will result in broken CSV. What's the issue with .csvExport()?

The .csvFormat() method was generating incorrect time values.

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:77]: Try fixing the .csvExport(). I'm conservative about small time fixes because they fix one thing and break another two. We should implement the proper solution that I started in #3396. This converter works properly but must be used everywhere and also edge-cases like Time.MIN/MAX aren't handled gracefully

File: shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt [hunk 2]
```diff
@@ -187,8 +187,11 @@ class ExportCsvUseCase @Inject constructor(
         id = id
     )
 
-    private fun Instant.csvFormat(): String = convertToLocal()
-        .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
+    private fun Instant.csvFormat(): String {
+        return Instant.ofEpochMilli(this.toEpochMilli())
+            .atZone(ZoneId.of("UTC"))
```
Comment (ILIYANGERMANOV) [inline shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:192]: Let's export it at user's local time. Most non-dwv users aren't aware of UTC and will be confused. The goal should be to export the UTC time in DB to the correct local time regardless of the time zone

Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:192]: How about this : 
```
private fun Instant.csvFormat(): String {
    return Instant.ofEpochMilli(this.toEpochMilli())
        .atZone(ZoneId.systemDefault()) 
        .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME) 
}
```

File: shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt [hunk 3]
```diff
@@ -187,8 +187,9 @@ class ExportCsvUseCase @Inject constructor(
         id = id
     )
 
-    private fun Instant.csvFormat(): String = convertToLocal()
-        .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
+    private fun Instant.csvFormat(): String {
+        return this.atZone(ZoneId.of("UTC")).toLocalDateTime().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
```
[the remark this answers is not in the document]
Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:191]: > The user should see the CSV time in their local time

I tried this. but when i import the file then the app  again converts to local while importing  which leads to +5:30 ahead time after importing

[the remark this answers is not in the document]
Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:191]: Got it 👍 Let's export in UTC then

[the remark this answers is not in the document]
Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:191]: @akashs056 can you retest your latest changes and if it works ping me for re-review so I can merge them

[the remark this answers is not in the document]
Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:191]: @ILIYANGERMANOV i did my retest on my latest changes and i works perfectly fine

**Review by ILIYANGERMANOV — APPROVED** [review]
