### PR TITLE
fix-issue-3481

### LINKED ISSUE #3481: [BUG] Time Not Applied Correctly in Loans – Set Time Behind by 1 Hour (-1h)
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

In the loans section, the time is consistently behind by one hour (-1h) from the set value. This bug results in incorrect time being displayed for all loan entries.

### To Reproduce

1. Navigate to the loans section.
2. Set a specific time for a loan.
3. Observe that the displayed time is consistently behind by 1 hour from the time that was set.

### Expected behavior

The time should match the exact value set for the loan.

### Screenshots

https://github.com/user-attachments/assets/3c9db962-9367-45ef-9cfb-7990cded3126

### App version

v2024.09.01

### Smartphone

Xiaomi redmi 10, Android 11

### Additional context

Please check the attached video for a more detailed demonstration of the issue.

### PR DESCRIPTION
**Pull request by akashs056**
## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## Screen recording of your changes (if applicable):

https://github.com/user-attachments/assets/349091c1-3b90-4aea-931b-1f55376d3bfe

## What's changed?

used the new Time Provider APIs 

Before|After
---|---
{media}|{media}
{media}|{media}

## Risk factors

**What may go wrong if we merge your PR?**
- ...
- ...

**In what cases won't your code work?**
- ...
- ...

## Does this PR close any GitHub issues? (do not delete)

- Closes #3481

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: app/src/main/java/com/ivy/wallet/RootActivity.kt [hunk 1]
```diff
@@ -210,7 +208,7 @@ class RootActivity : AppCompatActivity(), RootScreen {
     private fun setupTimePicker() {
         ivyContext.onShowTimePicker = { initialTime,
                                         onTimePicked ->
-            val nowLocal = initialTime ?: timeNowLocal().toLocalTime()
+            val nowLocal = initialTime ?: timeProvider.localTimeNow()
             val is24Hour = android.text.format.DateFormat.is24HourFormat(this)
```
Comment (ILIYANGERMANOV) [inline app/src/main/java/com/ivy/wallet/RootActivity.kt:212]: This date-time picker should be deleted and fully migrated to `DeviceDateTimePicker`

File: screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt [hunk 2]
```diff
@@ -793,18 +792,20 @@ private fun InitialRecordItem(
...
-                style = UI.typo.nC.style(
-                    color = Gray,
-                    fontWeight = FontWeight.Bold
-                )
+        val timeFormatter = LocalTimeFormatter.current
+
+        Text(
+            modifier = Modifier.padding(horizontal = 24.dp),
+            text = with(timeFormatter) {
+                loan.dateTime!!.format(
```
Comment (ILIYANGERMANOV) [inline screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt:800]: `!!` will cause a crash 😬 Handle the null case properly

Comment (ILIYANGERMANOV) [reply screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsScreen.kt:800]: If null => don't show the text

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt [hunk 3]
```diff
@@ -40,22 +42,24 @@ fun DateTimeRow(
             iconStart = R.drawable.ic_date
         ) {
             ivyContext.datePicker(
-                initialDate = dateTime.convertUTCtoLocal().toLocalDate()
+                initialDate = with(timeConverter) { dateTime.toLocalDate() }
```
Comment (ILIYANGERMANOV) [inline temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt:45]: Move the date-time picking to the VM, see `EditTransactionViewModel` and how it does it using the new datetime picker

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt [hunk 4]
```diff
@@ -40,22 +42,24 @@ fun DateTimeRow(
...
         IvyOutlinedButton(
-            text = dateTime.formatLocalTime(),
+            text = with(timeFormatter) {
+                dateTime.toLocalTime().format()
+            },
             iconStart = R.drawable.ic_date
         ) {
             ivyContext.timePicker(
-                initialTime = dateTime.convertUTCtoLocal().toLocalTime()
+                initialTime = with(timeConverter) { dateTime.toLocalTime() }
```
Comment (ILIYANGERMANOV) [inline temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt:60]: Same here, use the new picker

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]

**Comment by akashs056** [comment]
@ILIYANGERMANOV I’ve migrated the default time picker to the new one, but I’m facing an issue. When I update the time from the ViewModel using the loan record dateTime, it works fine in edit mode. However, when creating a new record and `loanRecordModalData.value.loanRecord` is null, the time doesn’t update properly. Should I create a separate state for handling this time, or do you have any other suggestions? Please take a look at the code.

**Comment by suyash01** [comment]
> @ILIYANGERMANOV I’ve migrated the default time picker to the new one, but I’m facing an issue. When I update the time from the ViewModel using the loan record dateTime, it works fine in edit mode. However, when creating a new record and `loanRecordModalData.value.loanRecord` is null, the time doesn’t update properly. Should I create a separate state for handling this time, or do you have any other suggestions? Please take a look at the code.

handling for save and edit scenarios is present [here](https://github.com/Ivy-Apps/ivy-wallet/blob/0d9a484564237aee4eaface25a05853b997d7d61/temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanRecordModal.kt#L386-L433)

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt [hunk 5]
```diff
@@ -39,24 +38,18 @@ fun DateTimeRow(
             text = dateTime.formatNicely(),
             iconStart = R.drawable.ic_date
         ) {
-            ivyContext.datePicker(
-                initialDate = dateTime.convertUTCtoLocal().toLocalDate()
-            ) {
-                onSetDateTime(getTrueDate(it, dateTime.toLocalTime()))
-            }
+            onEditDate()
```
[the remark this answers is not in the document]
Comment (ILIYANGERMANOV) [reply temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/components/DateTimeRow.kt:41]: +1

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt [hunk 6]
```diff
@@ -209,9 +211,8 @@ fun BoxWithConstraintsScope.LoanModal(
 
         DateTimeRow(
             dateTime = dateTime,
-            onSetDateTime = {
-                dateTime = it
-            }
+            onEditDate = {},
+            onEditTime = {}
```
[the remark this answers is not in the document]
Comment (ILIYANGERMANOV) [reply temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt:215]: @akashs056 does the code work w/o this handling?

**Review by ILIYANGERMANOV — APPROVED** [review]
Provide a screen recording after the latest changes and we can merge

File: temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt (hunk 6 above)
[the remark this answers is not in the document]
Comment (akashs056) [reply temp/legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/LoanModal.kt:215]: yes i didnt implemented the loan model yet.. i was just migrating the loan record model but will do that once this one is over...the migration isnt fully over yet

File: screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt [hunk 7]
```diff
@@ -449,6 +462,46 @@ class LoanDetailsViewModel @Inject constructor(
...
+            updateDateTime(localDate.atTime(localTime))
+        }
+    }
+
+    private fun updateDateTime(newDateTime: LocalDateTime) {
+        val newDateTimeUtc = with(timeConverter) { newDateTime.toUTC() }
+        loanRecordModalData.value?.let { currentData ->
+            loanRecordModalData.value = currentData.copy(
+                loanRecord = currentData.loanRecord?.copy(
+                    dateTime = newDateTimeUtc
```
Comment (akashs056) [inline screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt:499]: @ILIYANGERMANOV The problem is that this changes is working when this ` loanRecord = currentData.loanRecord?` is not null that means when we are in editing a record it works perfectly fine,,, but while creating a new record the time and date doesnt gets updated because `loanRecord = currentData.loanRecord?` this is null........... please see the attached vedio for detail 
 
https://github.com/user-attachments/assets/eb0e172a-0cf3-4af2-8e2e-f01781479eb2

**Comment by akashs056** [comment]
> Provide a screen recording after the latest changes and we can merge

The latest changes is not working as expected see i am commented the issue oi am facing please suggest your opinion should i modify the states or any other approach.....

File: screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt (hunk 7 above)
Comment (ILIYANGERMANOV) [reply screen/loans/src/main/java/com/ivy/loans/loandetails/LoanDetailsViewModel.kt:499]: I don't have enough context, see how it's solved in `EditTransactionViewModel`. For example, you save the dateTime in a `mutableStateOf()` that's initialized to `record.dateTime ?: timeNow`

**Comment by akashs056** [comment]
Screen recording of my latest changes and works perfectly fine 

https://github.com/user-attachments/assets/8efdca7a-c29d-4114-8fe9-3f4044425864

**Review by ILIYANGERMANOV — APPROVED** [review]
