### PR TITLE
fix csv export

### LINKED ISSUE #3422: [BUG] Incorrect time shown in exported csv file
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

This is a transaction in the Ivy Wallet app
[Image 1]
And this is the same transaction in the csv file. 
[Image 2]
I think this issue might be related to #3402 

### To Reproduce

1. Go to settings
2. Export CSV File
3. Some transactions have incorrect time.

### Expected behavior

_No response_

### Image 1
WhatsApp Image 2024-08-23 at 13 30 49_590b7206
### Image 2
image

### App version

v2024.07.28(194) from Google Play

### Smartphone

Poco F3 GT, Android 13

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by akashs056**
## Pull request (PR) checklist

Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## What's changed?

Describe with a few bullets **what's new:**

fixed this issue #3422  previously by #3426 
but after the time issue if fixed by #3435  its works incorrectly it exports time at UTC and does not converts it to Local time 
So, with this changes its now working perfectly fine exports in users local time and aslo imports in local time zone without any issue

Before|After
---|---
{media}|{media}
{media}|{media}

## Risk factors

**What may go wrong if we merge your PR?**
- ...
- ...

**In what cases won't your code work?**
- ...
- ...

## Does this PR close any GitHub issues? (do not delete)

- Closes #3422 

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt [hunk 1]
```diff
@@ -188,7 +189,8 @@ class ExportCsvUseCase @Inject constructor(
     )
 
     private fun Instant.csvFormat(): String {
-        return this.atZone(ZoneId.of("UTC")).toLocalDateTime().format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
+        return this.atZone(timeProvider.getZoneId())
+            .format(DateTimeFormatter.ISO_LOCAL_DATE_TIME)
```
Comment (ILIYANGERMANOV) [inline shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: Thinking again for the export it makes more sense to keep the time in UTC

Comment (akashs056) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: after the time issue if fixed by https://github.com/Ivy-Apps/ivy-wallet/pull/3435 it works incorrectly it exports time at UTC and does not converts it to Local time after importing which results in incorrect time after importing

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: Can you add a new method to the `TimeConverter`:
```
fun Instant.toUTC(): LocalDateTime 
```
 and use it in this function. This method must also be unit tested, similarly to the other  `TimeConverter` ones

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Left some comments:
1. Export CSV time in UTC
2. Use the `TimeConverter` API

File: shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt (hunk 1 above)
Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: If you think exporting in local time is a good idea, again use the `TimeConverter` API

All time conversions should be centralized via it. Otherwise, we'll continue to run through all the same time problems

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: Usage:
```kotlin
with(timeConverter) { instant.toLocal() }
```

Comment (ILIYANGERMANOV) [reply shared/domain/src/main/java/com/ivy/domain/usecase/csv/ExportCsvUseCase.kt:193]: Got it @akashs056. Thanks for the fix! Let's use the TimeConverter and we can merge

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice! 💯

**Comment by ILIYANGERMANOV** [comment]
@akashs056 you neee to fix the `ExportCsvUseCase` unit tests by providing a mocked TimeConverter impl

**Comment by ILIYANGERMANOV** [comment]
> @akashs056 you neee to fix the `ExportCsvUseCase` unit tests by providing a mocked TimeConverter impl

Or even better and easier, create a `TestTimeConverter` impl that converts always to UTC. I mean in it you hard-code the current timezone to UTC. Does that makes sense?

**Review by shamim-emon — APPROVED** [review]

**Comment by akashs056** [comment]
@ILIYANGERMANOV, I've implemented a `TestTimeConverter `that hard-codes the current timezone to UTC as you suggested. Could you please confirm if this is the correct approach? I'm still new to unit testing, so I want to make sure I'm on the right track.

File: shared/base/src/main/java/com/ivy/base/time/impl/TestTimeConverter.kt [hunk 2]
```diff
@@ -0,0 +1,27 @@
+package com.ivy.base.time.impl
+
+import com.ivy.base.time.TimeConverter
+import java.time.Instant
+import java.time.LocalDate
+import java.time.LocalDateTime
+import java.time.ZoneId
+
+class TestTimeConverter : TimeConverter {
```
Comment (ILIYANGERMANOV) [inline shared/base/src/main/java/com/ivy/base/time/impl/TestTimeConverter.kt:9]: Looks correct 💯

**Comment by ILIYANGERMANOV** [comment]
@akashs056 you have a build error 
e: file:///home/runner/work/ivy-wallet/ivy-wallet/shared/base/src/main/java/com/ivy/base/time/impl/TestTimeConverter.kt:9:1 Class 'TestTimeConverter' is not abstract and does not implement abstract member 'toLocalTime'.

The TestTimeConveter will be red

**Comment by akashs056** [comment]
> @akashs056 you have a build error e: file:///home/runner/work/ivy-wallet/ivy-wallet/shared/base/src/main/java/com/ivy/base/time/impl/TestTimeConverter.kt:9:1 Class 'TestTimeConverter' is not abstract and does not implement abstract member 'toLocalTime'.
> 
> The TestTimeConveter will be red

I've resolved the initial error with the TestTimeConverter class in my local build. However, now I'm encountering a UncompletedCoroutinesError in the test property - num of row and columns matches the format. It seems to be related to the coroutine not completing within the expected time

**Comment by ILIYANGERMANOV** [comment]
@akashs056 push it so I can have a look - the CI will also provide feedback

**Comment by akashs056** [comment]
@ILIYANGERMANOV getting the same error again

File: shared/domain/src/test/java/com/ivy/domain/usecase/csv/ExportCsvUseCasePropertyTest.kt [hunk 3]
```diff
@@ -20,6 +21,8 @@ import io.kotest.property.arbitrary.next
 import io.kotest.property.checkAll
 import io.mockk.coEvery
 import io.mockk.mockk
+import kotlinx.coroutines.ExperimentalCoroutinesApi
```
Comment (ILIYANGERMANOV) [inline shared/domain/src/test/java/com/ivy/domain/usecase/csv/ExportCsvUseCasePropertyTest.kt:24]: remove this imports, why we need them?

Comment (akashs056) [reply shared/domain/src/test/java/com/ivy/domain/usecase/csv/ExportCsvUseCasePropertyTest.kt:24]: i was just testing... will remove it

**Comment by akashs056** [comment]
sometimes when i run locally with the same code i does not gives any error 
image

**Comment by ILIYANGERMANOV** [comment]
@akashs056 fix build errors, update branch and tests should pass on the CI 🤞 I don't see anything incorrect

**Comment by akashs056** [comment]
@ILIYANGERMANOV Gradle error indicating that the `toLocalTime `method is not implemented, but I can’t find this method in the `TimeConverter `interface. The error has been persisting since yesterday, and I’m having trouble resolving it. Could you please help me understand what might be going wrong?

**Comment by ILIYANGERMANOV** [comment]
> @ILIYANGERMANOV Gradle error indicating that the `toLocalTime `method is not implemented, but I can’t find this method in the `TimeConverter `interface. The error has been persisting since yesterday, and I’m having trouble resolving it. Could you please help me understand what might be going wrong?

It's there, look into StandardTimeConveter. It was merged yesterday - update branch, git pull and open the implementation

**Comment by ILIYANGERMANOV** [comment]
@akashs056 now git pull and implement `TestTimeConverter` and everything should be ✅

**Review by ILIYANGERMANOV — APPROVED** [review]

**Comment by akashs056** [comment]
@ILIYANGERMANOV  Its ready to merge
