### PR TITLE
Fixed The Issue, Padding Changed Of Circular Keyboard Button

### LINKED ISSUE #2750: [BUG] Digits diaplacement on the keyboard buttons
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

I thought it was just an illusion, but it seems that the digits and other keyboard elements for the balance keyboard and calculator are not centered in the button outline. It's perfectly visible in the PR #2749 overview video. 

### To Reproduce

1. Add a transaction
2. Open a calculator

### Expected behavior

The numbers are correctly centered vertically and horizontally within the circle button outline.

### Screenshots

It's not that bad on my side, but some buttons still seem a little off.

@

### Smartphone

Samsung Galaxy S20 Ultra 

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by YatinGarg07**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x ] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md).
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] My code builds and is tested on a real Android device.
- [x] I confirm that I've run the code locally and everything works as expected.

## What's changed?

Changed the Padding of KeyboardCircleButton from only top side to all sides.
-  This way the element inside it will always be at Center aligned.

## ScreenShots
Screenshot_20231004_003534
WhatsApp Image 2023-10-04 at 00 47 10_4f1cfc41

## Risk Factors

**What may go wrong if we merge your PR?**

- The Issue is Not That Much Critical, Just Enhances User Experiences

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues] (https://github.com/Ivy-Apps/ivy-wallet/assets/73949161/d3b15073-3140-434c-b18a-a2f70838c609
/github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2750

### CODE REVIEW

File: temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt [hunk 1]
```diff
@@ -501,7 +501,7 @@ fun KeypadCircleButton(
 ) {
     Text(
         modifier = circleButtonModifier(size = btnSize, onClick = onClick)
-            .padding(top = 10.dp)
+            .padding(13.dp)
```
Comment (ILIYANGERMANOV) [inline temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt:504]: Can you make the padding `top` only? Otherwise we add padding on all 4 sides which risks the number on the button to become cut.

**Review by ILIYANGERMANOV — COMMENTED** [review]
The buttons still doesn't look perfectly centered. However, that's an issue with our shitty font that should get fixed after we change it

**Comment by YatinGarg07** [comment]
It is good to know that you have identified the issue
But this workaround can help, till the time being we fix the font.
If there anything i can do please ask.

**Comment by ILIYANGERMANOV** [comment]
> It is good to know that you have identified the issue But this workaround can help, till the time being we fix the font. If there anything i can do please ask.

Just fix the comment that I left for `top =` and I think your PR is a step in the right direction so we'll merge it

**Comment by YatinGarg07** [comment]
@ILIYANGERMANOV 
Please review these changes and help me merge the branch into main

File: temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt (hunk 1 above)
Comment (ILIYANGERMANOV) [inline temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt:504]: Use `top = 13.dp`. Otherwise the app may break.

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]

File: temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt (hunk 1 above)
Comment (YatinGarg07) [reply temp-legacy-code/src/main/java/com/ivy/legacy/legacy/ui/theme/modal/edit/AmountModal.kt]: Required changes Made Successfully

**Review by YatinGarg07 — COMMENTED** [review]
Changes Have Been made. Please proceed with the necessary steps.

**Review by ILIYANGERMANOV — APPROVED** [review]
Thank you for making the changes!
