### PR TITLE
[IVY-2891] Fix Loan Migration Failure

### LINKED ISSUE #2891: [BUG] Loan Migration failure
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Loan Migration is failing.

### To Reproduce

1.  git reset  --hard 7e164455 
2. Add data with loans (a few transactions)
3. git pull (latest with main)
4. run

### Expected behavior

Migration should proceed Normally 

### Screenshots

_No response_

### Smartphone

AVD Pixel Android 10

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the "Contributing Rules".
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?

Fixes the App crash when updating from a very old apk

Describe with a few bullets **what's new:**
- a
- b
- c
- d

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b
- c

**In what cases your code won't work?**

- a
- b
- c

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #2891 

> Replace `ISSUE_NUMBER` with your issue number (for example Closes #1234). If you've done that correctly, you'll see the issue title linked when previewing your PR description.

## Troubleshooting CI failures

If you see any of the PR checks failing (❌) go to [Actions](https://github.com/Ivy-Apps/ivy-wallet/actions) and find it there. Or simply click "Details" next to the failed check and explore the logs to see why it has failed.

### Detekt
[Detekt](https://detekt.dev/) is a static code analyzer for Kotlin that we use to enforce code readibility and good practices.

**To run Detekt locally:**
```
./gradlew detekt
```

If the Detekt errors are caused by a legacy code, you can suppress them using a basline.

**Detekt baseline** (not recommended)
```
./scripts/detektBaseline.sh
```

### Lint

We use the [standard Android Lint](https://developer.android.com/studio/write/lint) plus [Slack's compose-lints](https://slackhq.github.io/compose-lints/) as an addition to enforce proper Compose usage.

**To run Lint locally:**
```
./scripts/lint.sh
```

If the Lint errors are caused by a legacy code, you can suppress them using a basline.

**Lint baseline** (not recommended)
```
./scripts/lintBaseline.sh
```

### Unit tests

If this job is failing this means that your changes break an existing unit test. You must identify the failing tests and fix your code.

**To run the Unit tests locally:**
```
./gradlew testDebugUnitTest
```

### CODE REVIEW

**Review by ILIYANGERMANOV — APPROVED** [review]
Thanks for the fix! 💯  Just fix the Detekt warning and we can merge
/home/runner/work/ivy-wallet/ivy-wallet/ivy-data/src/main/java/com/ivy/data/db/migration/Migration124to125_LoanEditDateTime.kt:16:1: Line detected, which is longer than the defined maximum line length in the code style. [MaxLineLength]

File: ivy-data/src/main/java/com/ivy/data/db/migration/Migration124to125_LoanEditDateTime.kt [hunk 1]
```diff
@@ -13,7 +13,7 @@ class Migration124to125_LoanEditDateTime : Migration(124, 125) {
         db.execSQL(
             "CREATE TABLE `${LOANS_TEMP_TABLE}` (`name` TEXT NOT NULL, `amount` REAL NOT NULL, `type` TEXT NOT NULL, `color` INTEGER NOT NULL, `icon` TEXT, `orderNum` REAL NOT NULL, `accountId` TEXT, `isSynced` INTEGER NOT NULL, `isDeleted` INTEGER NOT NULL, `dateTime` INTEGER, `id` TEXT NOT NULL, PRIMARY KEY(`id`))"
         )
-        db.execSQL("INSERT INTO `${LOANS_TEMP_TABLE}` SELECT * FROM `${LOANS_TABLE}`")
+        db.execSQL("INSERT INTO `${LOANS_TEMP_TABLE}` (name, amount, type, color, icon, orderNum, accountId, isSynced, isDeleted, dateTime, id ) SELECT name, amount, type, color, icon, orderNum, accountId, isSynced, isDeleted, dateTime, id FROM `${LOANS_TABLE}`")
```
Comment (ILIYANGERMANOV) [inline ivy-data/src/main/java/com/ivy/data/db/migration/Migration124to125_LoanEditDateTime.kt:16]: Extract `val columns = "name, amount, type, color, icon, orderNum, accountId, isSynced, isDeleted, dateTime, id` and re-use it. This will solve both the Detekt error and also make to code nicer and more stable

Comment (Vishwa-Raghavendra) [reply ivy-data/src/main/java/com/ivy/data/db/migration/Migration124to125_LoanEditDateTime.kt]: Done
