### PR TITLE
Fix error when the user clicks "Skip-Skip" default categories aren't added

### LINKED ISSUE #3056: [BUG][Onboarding] When the user clicks "Skip-Skip" default categories aren't added
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Default categories during onboarding aren't added. 

### To Reproduce

1. Clear data (open fresh install)
2. Click Offline Account
3. Click Start Fresh
4. Skip
5. Skip
6. Open the categories screen

### Expected behavior

After clicking "Skip" - "Skip" the default categories should be added.

### Screenshots

_No response_

### Smartphone

Doesn't matter

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by isaacnguyen0809**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

Result:

https://github.com/Ivy-Apps/ivy-wallet/assets/57831153/523922dc-aee0-4cef-a44f-af4121e6bbb9

## What's changed?

- Using categoryRepository instead of WriteCategoryDao for function preloadCategory

## Risk Factors

No risk factors

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3056

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/PreloadDataLogic.kt [hunk 1]
```diff
@@ -171,17 +178,23 @@ class PreloadDataLogic @Inject constructor(
...
-        val category = Category(
-            name = data.name,
-            color = data.color.toArgb(),
-            icon = data.icon,
-            orderNum = categoryOrderNum++,
-            isSynced = false
-        )
+        val category: Category? = either {
+            Category(
+                name = NotBlankTrimmedString.from(data.name.trim()).bind(),
```
Comment (ILIYANGERMANOV) [inline temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/PreloadDataLogic.kt:185]: no need for `.trim()` the `NotBlankTrimmedString` does it for us

**Review by ILIYANGERMANOV — APPROVED** [review]

File: temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/PreloadDataLogic.kt (hunk 1 above)
Comment (isaacnguyen0809) [reply temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/PreloadDataLogic.kt]: Updated
