### PR TITLE
Fix issue 3370

### LINKED ISSUE #3370: [BUG] Implement pagination for the "Contributors" screen
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Currently we show only the Top 100 contributors within the "Contributors" screen. 

### To Reproduce

1. Open the Contributors scree from Settings
2. Observe only 100 contributors are shown.

### Expected behavior

All GitHub contributors are displayed and the correct number is visible in the toplbar.
Note: do **not** add new libraries to the project. You might need to implement a new GitHub API request to fetch the exact number of contributors.

### Screenshots

_No response_

### App version

any version

### Smartphone

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by rodrigoliveirac**
## Pull request (PR) checklist
Please check if your pull request fulfills the following requirements:

- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read and understand the [Developer Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Guidelines.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] My PR includes only the necessary changes to fix the issue (i.e., no unnecessary files or lines of code are changed).
- [x] 🎬 I've attached a **screen recording** of using the new code to the next paragraph (if applicable).

## What's changed?
Describe with a few bullets **what's new:**
- The issue was due to using a query that only fetched the maximum number of contributors specified by the `per_page` parameter. We are now also using the `page` parameter for pagination and including anonymous contributors with the `anon` parameter. 
- To include anonymous contributors, we needed to make the fields in the ContributorDto model nullable, with null as the default value.

## Risk factors
**What may go wrong if we merge your PR?**
- In the future, we should consider implementing paging in the UI to prevent users from waiting too long.

## Does this PR close any GitHub issues? (do not delete)
- Closes #3370 

## Troubleshooting GitHub Actions (CI) failures ❌
Pull request checks failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 1]
```diff
@@ -38,19 +39,48 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
         private const val CONTRIBUTORS_PER_PAGE = 100
+        private const val DISPLAY_ANONYMOUS_CONTRIBUTORS = true
+        private const val INITIAL_PAGE = 1
     }
 
-    suspend fun fetchContributors(): List<ContributorDto>? {
-        return try {
-            withContext(Dispatchers.IO) {
+    suspend fun fetchContributors(): List<ContributorDto> {
+        return withContext(Dispatchers.IO) {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:47]: Can we use `dispatchersProvider.io` so the code is unit testable

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 2]
```diff
@@ -38,19 +39,48 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+                Timber.tag("FETCH_CONTRIBUTORS").d(e)
+                null
             }
-        } catch (e: Exception) {
+            currentPage = getCurrentPage(contributors, currentPage)
+            currentPage?.let { addContributors(contributors) }
+        }
+    }
+
+    private fun getCurrentPage(
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:76]: rename this to get `getNextPage`

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt [hunk 3]
```diff
@@ -49,22 +49,18 @@ class ContributorsViewModel @Inject constructor(
...
+                githubProfileUrl = it.link ?: ""
             )
         }
 
-        if (contributors != null) {
-            contributorsResponse.value = ContributorsResponse.Success(
-                contributors.toImmutableList()
-            )
-        } else {
-            contributorsResponse.value = ContributorsResponse.Error("Error")
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:66]: Do we support an error case? What do we show if there's no internet?

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 4]
```diff
@@ -38,19 +39,48 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+        contributors: List<ContributorDto>?,
+        currentPage: Int
+    ): Int? {
+        return if (contributors?.isEmpty() == true) {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:80]: nit: we can make it shorter by `= if ()...` w/o the return

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 5]
```diff
@@ -38,19 +39,48 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+        }
+    }
+
+    private suspend fun paging(addContributors: (List<ContributorDto>?) -> Unit) {
+        var currentPage: Int? = INITIAL_PAGE
+        while (currentPage != null) {
+            val contributors = try {
                 httpClient
                     .get("https://api.github.com/repos/Ivy-Apps/ivy-wallet/contributors") {
+                        parameter("anon", DISPLAY_ANONYMOUS_CONTRIBUTORS)
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: Let's extract the HTTP request in another function and make it return `Either`

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt (hunk 1 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:47]: Sure!

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt (hunk 3 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:66]: That's true. I missed that, sorry. I'll fix it.

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt (hunk 5 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: What you think about this? :

```
suspend fun fetchContributors(): Result<List<ContributorDto>> {
        return withContext(dispatchersProvider.io) {
            try {
                val contributors = mutableListOf<ContributorDto>()
                paging(addContributors = { results ->
                    results?.forEach { contributor -> contributors.add(contributor) }
                })
                Result.success(contributors)
            } catch (e: Exception) {
                Timber.tag("FETCH_CONTRIBUTORS_PAGING").d(e)
                Result.failure(e)
            }
        }
    }

private suspend fun paging(addContributors: (List<ContributorDto>?) -> Unit) {
        var currentPage: Int? = INITIAL_PAGE
        while (currentPage != null) {
            val contributors = getContributorsFromRequest(currentPage)
            currentPage = getNextPage(contributors.getOrThrow(), currentPage)
            currentPage?.let { addContributors(contributors.getOrThrow()) }
        }
    }

private suspend fun getContributorsFromRequest(currentPage: Int): Result<List<ContributorDto>> =
        try {
            val contributors = httpClient
                .get("https://api.github.com/repos/Ivy-Apps/ivy-wallet/contributors") {
                    parameter("anon", DISPLAY_ANONYMOUS_CONTRIBUTORS)
                    parameter("per_page", CONTRIBUTORS_PER_PAGE)
                    parameter("page", currentPage)
                }
                .body<List<ContributorDto>>()
            Result.success(contributors)
        } catch (e: Exception) {
            Timber.tag("FETCH_CONTRIBUTORS_REQUEST").d(e)
            Result.failure(e)
        }

```

So the viewmodel will call `fetchContributors` and perform it in this way: 

```
val contributorsResult = ivyWalletRepositoryDataSource.fetchContributors()

contributorsResult
            .onSuccess { contributorsDto ->
                val contributors = contributorsDto.map {
                    Contributor(
                        name = it.login ?: "Anonymous",
                        photoUrl = it.avatarUrl ?: "",
                        contributionsCount = it.contributions.toString(),
                        githubProfileUrl = it.link ?: ""
                    )
                }
                contributorsResponse.value = ContributorsResponse.Success(
                    contributors.toImmutableList()
                )
            }
            .onFailure { throwable ->
                contributorsResponse.value = ContributorsResponse.Error(
                    throwable.message.toString()
                )
            }
``

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: Can you change the code so I can comment 😅 LGTM, a few small nits:
- We use `Either` from Arrow instead of `Result` (check the dev guidelines for the reasoning)
- You can contributorsResult.fold()
- Don't throw exceptions
- Can we use `addAll` here to simplify it? 1 results?.forEach { contributor -> contributors.add(contributor)`

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: @rodrigoliveirac check this out https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/guidelines/Error-Handling.md

The benefit of Either is that we're not limited to `Throwable` error type

Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: > Can you change the code so I can comment 😅 LGTM, a few small nits:
> 
> * We use `Either` from Arrow instead of `Result` (check the dev guidelines for the reasoning)
> * You can contributorsResult.fold()
> * Don't throw exceptions
> * Can we use `addAll` here to simplify it? 1 results?.forEach { contributor -> contributors.add(contributor)`

Sure! I have a question about another topic: Detekt throws an error about the default values that I put in ContributorDto because the 'Anonymous' one comes null. What's the best approach to resolve that?

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: It's an failure in our Detekt check, default values are fine for DTOs, use `Suppress`

Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:62]: Ok. Thanks!

File: buildSrc/src/main/kotlin/ivy.script.gradle.kts [hunk 6]
```diff
@@ -12,8 +12,8 @@ kotlin {
 }
 
 tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile>().configureEach {
-    kotlinOptions {
-        freeCompilerArgs += "-XXLanguage:+ContextReceivers"
+    compilerOptions {
```
Comment (ILIYANGERMANOV) [inline buildSrc/src/main/kotlin/ivy.script.gradle.kts:15]: Why did you change this? Let's revert it if there's no special purpose

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt [hunk 7]
```diff
@@ -49,22 +49,25 @@ class ContributorsViewModel @Inject constructor(
...
-                name = it.login,
-                photoUrl = it.avatarUrl,
-                contributionsCount = it.contributions.toString(),
-                githubProfileUrl = it.link
-            )
-        }
+        val contributorsResult = ivyWalletRepositoryDataSource.fetchContributors()
 
-        if (contributors != null) {
+        contributorsResult.fold({ errorMessage ->
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:54]: Add named arguments to the `fold` so it's readable. And follow the order of the arguments as defined in the fold function

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 8]
```diff
@@ -33,26 +38,61 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+                currentPage = getNextPage(results, currentPage)
+                currentPage?.let { contributorsSource.addAll(results) }
+            })
+            if (currentPage == null) { break }
+        }
+        contributorsSource.toList()
+    }
+
+    private suspend fun getContributorsFromRequest(currentPage: Int): Either<String, List<ContributorDto>> =
+        either {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:78]: There's built-in `catch({}){ e -> }` in Arrow for that purpose

File: screen/contributors/src/test/java/com/ivy/contributors/ContributorsViewModelTest.kt [hunk 9]
```diff
@@ -26,20 +27,22 @@ class ContributorsViewModelTest : ComposeViewModelTest() {
...
-                link = "a_link"
-            ),
-            ContributorDto(
-                login = "b",
-                avatarUrl = "b_avatar",
-                contributions = 42,
-                link = "b_link"
-            ),
-        )
+        coEvery { repoDataSource.fetchContributors() } returns either {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/test/java/com/ivy/contributors/ContributorsViewModelTest.kt:30]: returns Either.Right(...)

File: screen/contributors/src/test/java/com/ivy/contributors/ContributorsViewModelTest.kt [hunk 10]
```diff
@@ -78,7 +81,7 @@ class ContributorsViewModelTest : ComposeViewModelTest() {
     @Test
     fun `unhappy path, both error`() {
         // given
-        coEvery { repoDataSource.fetchContributors() } returns null
+        coEvery { repoDataSource.fetchContributors() } returns either { raise("Error") }
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/test/java/com/ivy/contributors/ContributorsViewModelTest.kt:84]: returns Either.Left("Error")

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 11]
```diff
@@ -33,26 +38,61 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+            }
+        }
+    }
+
+    private suspend fun pagingSource(): Either<String, List<ContributorDto>> = either {
+        val contributorsSource = mutableListOf<ContributorDto>()
+        var currentPage: Int? = INITIAL_PAGE
+        while (currentPage != null) {
+            val contributorsResult = getContributorsFromRequest(currentPage)
+            contributorsResult.fold({ errorMessage ->
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:65]: Here, `.onLeft` and `onRight` would be more appropriate than `fold` because we do only side-effects and don't map the result.

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 12]
```diff
@@ -33,26 +38,61 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
     }
 
-    suspend fun fetchContributors(): List<ContributorDto>? {
-        return try {
-            withContext(Dispatchers.IO) {
+    suspend fun fetchContributors(): Either<String, List<ContributorDto>> = either {
+        withContext(dispatchersProvider.io) {
+            try {
+                pagingSource().bind()
+            } catch (e: Exception) {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:54]: This `try-catch` should be unnecessary? Why do we need it? The `pagingSource` should be already a total function and never throw. It should be just withContext() and call to the pagingSource

**Review by ILIYANGERMANOV — CHANGES_REQUESTED** [review]
Left some more comments. Thanks for migrating it to FP-style and Arrow!

File: buildSrc/src/main/kotlin/ivy.script.gradle.kts (hunk 6 above)
Comment (rodrigoliveirac) [reply buildSrc/src/main/kotlin/ivy.script.gradle.kts:15]: Detekt reported that `kotlinOptions` is deprecated and suggests using the `compilerOptions` DSL

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt (hunk 7 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:54]: Ok

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt (hunk 12 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:54]: Yes, I was unsure about that because of the `nextPage` function, which can return null results. But since null results come from the left side, this should not cause any issues. So you're right! I’ll write some tests

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:54]: Tests ftw!

File: buildSrc/src/main/kotlin/ivy.script.gradle.kts (hunk 6 above)
Comment (ILIYANGERMANOV) [reply buildSrc/src/main/kotlin/ivy.script.gradle.kts:15]: Got it. Thanks! 💯

**Comment by rodrigoliveirac** [comment]
> Left some more comments. Thanks for migrating it to FP-style and Arrow!

My pleasure! I’ll study this concept further

File: screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+import com.ivy.contributors.IvyWalletRepositoryDataSource.ContributorDto
+import com.ivy.contributors.ktor.IvyMockEngine
+import io.kotest.matchers.shouldBe
+import io.ktor.client.plugins.contentnegotiation.ContentNegotiation
+import io.ktor.serialization.kotlinx.json.json
+import io.mockk.coEvery
+import io.mockk.spyk
+import kotlinx.coroutines.test.runTest
+
+class ContributorsDataSourceTest {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:17]: @rodrigoliveirac just use `mockk` for the unit tests

If you're creating integration tests there should be way simpler way. This seems like an overkill

**Comment by ILIYANGERMANOV** [comment]
@rodrigoliveirac also make sure to check this:
- https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/guidelines/Unit-Testing.md
- The tests for fetching exchange rate

File: screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt (hunk 13 above)
Comment (ILIYANGERMANOV) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:17]: For reference:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/shared/domain/src/androidTest/java/com/ivy/domain/usecase/SyncExchangeRatesUseCaseTest.kt

Comment (rodrigoliveirac) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:12]: > @rodrigoliveirac just use `mockk` for the unit tests
> 
> If you're creating integration tests there should be way simpler way. This seems like an overkill

Are you referring to the `FakeDataSource`? We can't use mockk with `HttpClient`. I'm updating the tests and to use the our real HttpClient.

Comment (ILIYANGERMANOV) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:12]: Why we can't mockk `HttpClient`? It's a bit harder but possibly. If you want to use the real HttpClient this must be an androidTest that runs on an emulator. Btw @rodrigoliveirac if it's too hard to add, it's fine leaving it w/o a test

Comment (rodrigoliveirac) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:12]: Because we're leading with this issue https://github.com/mockk/mockk/issues/571

Comment (ILIYANGERMANOV) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:12]: got it, thanks

Comment (ILIYANGERMANOV) [reply screen/contributors/src/test/java/com/ivy/contributors/datasource/ContributorsDataSourceTest.kt:12]: @rodrigoliveirac if you decide to make it an `androidTest` then you'll also have to the Integration Tests GitHub Actions workflow to run it

**Comment by rodrigoliveirac** [comment]
@ILIYANGERMANOV To avoid unnecessary complexity, I’ve decided to leave this test unimplemented for now

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 14]
```diff
@@ -33,27 +39,59 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
+                currentPage = getNextPage(results, currentPage)
+                currentPage?.let { contributorsSource.addAll(results) }
+            }
+            if (currentPage == null) { break }
         }
+        contributorsSource.toList()
     }
 
+    private suspend fun getContributorsFromRequest(currentPage: Int): Either<String, List<ContributorDto>> =
+        either {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:76]: Remove `either` and return Either.Left() in the catch errro block.  `either {}` is redundant

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt [hunk 15]
```diff
@@ -49,22 +49,28 @@ class ContributorsViewModel @Inject constructor(
...
+        val contributorsResult = ivyWalletRepositoryDataSource.fetchContributors()
 
-        if (contributors != null) {
-            contributorsResponse.value = ContributorsResponse.Success(
-                contributors.toImmutableList()
-            )
-        } else {
-            contributorsResponse.value = ContributorsResponse.Error("Error")
-        }
+        contributorsResult.fold(
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:54]: contributorsResponse.value = contributorsResult.fold(...)

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt [hunk 16]
```diff
@@ -33,27 +39,59 @@ class IvyWalletRepositoryDataSource @Inject constructor(
...
 
-    suspend fun fetchContributors(): List<ContributorDto>? {
-        return try {
-            withContext(Dispatchers.IO) {
-                httpClient
-                    .get("https://api.github.com/repos/Ivy-Apps/ivy-wallet/contributors") {
-                        parameter("per_page", CONTRIBUTORS_PER_PAGE)
-                    }
-                    .body<List<ContributorDto>>()
+    suspend fun fetchContributors(): Either<String, List<ContributorDto>> = either {
```
Comment (ILIYANGERMANOV) [inline screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:51]: This `either` isn't needed

**Review by ILIYANGERMANOV — APPROVED** [review]
Left some comments about incorrect Arrow usages. Ping me to merge after they are resolved and the CI has passed

File: screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt (hunk 15 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:54]: Got it. We should use Either on the screen as well, right?

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/ContributorsViewModel.kt:54]: Read this:
https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/guidelines/Data-Modeling.md

Use ADTs, sealed interface with one for Loading, Success, Error

File: screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt (hunk 16 above)
Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:51]: We should use either {} to use the catch function and make the Either type explicit to avoid getting an `Any` type."

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:51]: Because in `catch` the last line of the lambdas must return `Either` - see other catch usages and the function signature

Comment (ILIYANGERMANOV) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:51]: `catch({ Either.Right(42) }){ Either.Left("err" ) }` you can use it like that @rodrigoliveirac

Comment (rodrigoliveirac) [reply screen/contributors/src/main/java/com/ivy/contributors/IvyWalletRepositoryDataSource.kt:51]: Ok. Thanks!

**Review by ILIYANGERMANOV — APPROVED** [review]
Nice work 👏 LGTM!
