### PR TITLE
Fix balance calculation if description and/or title are blank strings

### LINKED ISSUE #3025: [BUG] Account tab balance for some accounts it is not correct
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Data imported from the production application (v4.5.0) is not displayed correctly in the calculation of the balance of each account and the total.

Although the data import appears 100% correct and the transactions can be found in the history, the account does not include them and the value is incorrect.

The issue is related to empty fields on the backup file. I have verified that if an empty "description" filed is present on the json (see the example below) the transaction won't get added.

This might occur with other fields too but not checked.
[BugBackupFile.zip](https://github.com/Ivy-Apps/ivy-wallet/files/14643337/BugBackupFile.zip)

### To Reproduce

1. Create a transaction and click the description box. Exit that field without entering text.
2. Export the data and import it on the GitHub apk.
3. Check that the transaction is missing.
4. Check the backup file. The problematic transaction has an empty description field:
```json

{
         "accountId":"f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
         "type":"EXPENSE",
         "amount":60.0,
         "toAmount":60.0,
         "description":"",
         "dateTime":1710801631309,
         "categoryId":"ae92e17a-5cbd-47ab-bd2a-6f9d4f13744b",
         "id":"22744a09-1dbb-460c-a740-ca2cb194f32f"
      },
```

### Expected behavior

The balance of each account and the total balance should be calculated correctly. Taking every transaction into account.

### Screenshots

Stable

GitHub apk

### Smartphone

Pixel 7 Pro, Android 14
OnePlus 9, Android 13/14

### Additional context
The exported backup json with the issue example:
[BugBackupFile.zip](https://github.com/Ivy-Apps/ivy-wallet/files/14643349/BugBackupFile.zip)

### PR DESCRIPTION
**Pull request by Aritzherrero4**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [ ] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?
This patch fixes the account balance calculation in som edge cases after a backup is imported. Fixes errors in the following scenarios:

```json
    "transactions": [
        {
            "accountId": "f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
            "type": "EXPENSE",
            "title": ""
            "amount": 20.0,
            "toAmount": 20.0,
            "dateTime": 1710801642282,
            "categoryId": "7d0435cf-ee90-4717-b408-9ceba878f6ef",
            "id": "4bcd6bfd-6c42-438e-b75c-5b4c5d97df10"
        },
        {
            "accountId": "f5a6ecb3-6fb2-4fbf-ae66-4bd0e7e99aa9",
            "type": "EXPENSE",
            "amount": 60.0,
            "toAmount": 60.0,
            "description": "",
            "dateTime": 1710801631309,
            "categoryId": "ae92e17a-5cbd-47ab-bd2a-6f9d4f13744b",
            "id": "22744a09-1dbb-460c-a740-ca2cb194f32f"
        },
  ]
```
Describe with a few bullets **what's new:**
- Make title and description optional for TransactionMapper

## Risk Factors

**What may go wrong if we merge your PR?**

- No known risk.

**In what cases your code won't work?**

- No such scenario detected.

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3025

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt [hunk 1]
```diff
@@ -67,8 +67,8 @@ class TransactionMapper @Inject constructor() {
             TransactionType.EXPENSE -> {
                 Expense(
                     id = TransactionId(id),
-                    title = title?.let { NotBlankTrimmedString.from(it).bind() },
-                    description = description?.let { NotBlankTrimmedString.from(it).bind() },
+                    title = title?.let { NotBlankTrimmedString.from(it).getOrNull() },
```
Comment (ILIYANGERMANOV) [inline shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt:70]: Can we extract title and description as a variables so this code isn't duplicated 3 times?

**Review by ILIYANGERMANOV — APPROVED** [review]
LGTM! Fix the unit tests and we can merge

File: shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt (hunk 1 above)
Comment (Aritzherrero4) [reply shared/data/src/main/java/com/ivy/data/repository/mapper/TransactionMapper.kt]: Done
