### PR TITLE
Fix-Issue-2939

### LINKED ISSUE #2939: [BUG] Theme switching in the Quick Access menu doesn't work
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

Quick access theme switch does not work.

### To Reproduce

_No response_

### Expected behavior

Tapping the switch should toggle between the Auto/Light/Dark theme options.

### Screenshots

https://github.com/Ivy-Apps/ivy-wallet/assets/110673332/7c5ae417-70fd-4589-8315-431df9ddd760

### Smartphone

Galaxy s20+

### Additional context

Works well in the latest stable release.

### PR DESCRIPTION
**Pull request by michalguspiel**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

## What's changed?

- Implemented getSettingsWithNextTheme function in SettingsAct. Thanks to this change, codebase is a bit more DRY.
- Refactored SettingsViewModel and HomeViewModel to use this function when changing the theme.
- Changed `theme` in HomeViewModel to `currentTheme` to ensure consistency of naming in SettingsViewModel and HomeViewModel

https://github.com/Ivy-Apps/ivy-wallet/assets/70368829/9d61c4bb-5206-485c-b08d-f6edc7e5b687

## Risk Factors
- None I guess

## Does this PR closes any GitHub Issues?

- Closes #2939 

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/settings/SettingsAct.kt [hunk 1]
```diff
@@ -13,4 +14,14 @@ class SettingsAct @Inject constructor(
     override suspend fun Unit.compose(): suspend () -> Settings = suspend {
         io { settingsDao.findFirst() }
     } then { it.toDomain() }
-}
+
+    suspend fun getSettingsWithNextTheme(): Settings {
```
Comment (michalguspiel) [inline temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/settings/SettingsAct.kt:18]: I'm not sure if this is the best place for this function. I'm open to suggestions.

Comment (ILIYANGERMANOV) [reply temp/legacy-code/src/main/java/com/ivy/legacy/domain/action/settings/SettingsAct.kt:18]: It's fine, the legacy code is crappy

**Review by ILIYANGERMANOV — APPROVED** [review]
