### PR TITLE
[IVY-3037] Fix Accounts With Inital Balance

### LINKED ISSUE #3037: Can't create an account with InitialBalance
### Please confirm the following

- [X] I checked [the current issues](https://github.com/Ivy-Apps/ivy-wallet/issues) for duplicate problems

### Describe the bug

When creating an account, the initial balance entered is not being taken into account
We need to create an account and then manually go to the accounts page and enter initial balance to get the account with initial balance working

### To Reproduce

1. Create an Account with Initial balance
2. Go to Home tab  
(Account Initial Balance Transaction not seen)

### Expected behavior

Initial Balance Transaction should be seen

### Screenshots

_No response_

### Smartphone

Pixel 7a (Emulator)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vishwa-Raghavendra**
## Pull Request (PR) Checklist
Please check if your pull request fulfills the following requirements:
- [x] The PR is submitted to the `main` branch.
- [x] I've read the [Contribution Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/CONTRIBUTING.md) and my PR doesn't break the rules.
- [x] I've read the [Architecture Guidelines](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/Architecture.md).
- [x] I confirm that I've run the code locally and everything works as expected.
- [x] 🎬 I've attached a **screen recoding** of the changes. 

> Tip: drag & drop the video to the PR description.

## What's changed?

Describe with a few bullets **what's new:**
- a Accounts with Initial Balance can now be created.
- b
- c

> 💡 Tip: Please, attach screenshots and screen recordings. It helps a lot!

## Risk Factors

**What may go wrong if we merge your PR?**

- a
- b

**In what cases your code won't work?**

- a
- b

## Does this PR closes any GitHub Issues?

Check **[Ivy Wallet Issues](https://github.com/Ivy-Apps/ivy-wallet/issues)**.

- Closes #3037 

> Replace `ISSUE_NUMBER` with the number of the GitHub issue that this PR is fixing. If you've done that correctly, you'll see the issue title linked when previewing your PR description.

> **!Note:** Do **not** link the PR number. Link the number/id of the GitHub Issue from [issues](https://github.com/Ivy-Apps/ivy-wallet/issues).

## Troubleshooting CI failures ❌

GitHub Actions failing? Read our [CI Troubleshooting guide](https://github.com/Ivy-Apps/ivy-wallet/blob/main/docs/CI-Troubleshooting.md).

### CODE REVIEW

File: temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/AccountCreator.kt [hunk 1]
```diff
@@ -54,7 +54,8 @@ class AccountCreator @Inject constructor(
                 icon = data.icon,
                 includeInBalance = data.includeBalance,
                 orderNum = accountDao.findMaxOrderNum().nextOrderNum(),
-                isSynced = false
+                isSynced = false,
+                id = account.id.value
```
Comment (ILIYANGERMANOV) [inline temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/AccountCreator.kt:58]: Fckin default values caused this bug 😀 You see now why I'm banning them with Detekt. Thanks for fixing! Respect.

**Review by ILIYANGERMANOV — APPROVED** [review]

File: temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/AccountCreator.kt (hunk 1 above)
Comment (Vishwa-Raghavendra) [reply temp/legacy-code/src/main/java/com/ivy/legacy/domain/deprecated/logic/AccountCreator.kt:58]: Yes, now I get to know why default values cause so many problems xD

**Comment by ILIYANGERMANOV** [comment]
Merging after the CI pass ✅ Ping me if I forget to
